# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'camera', '~> 0.11.2'
  pod 'google_ml_kit', '~> 0.18.0'
  pod 'google_mlkit_translation', '~> 0.11.0'
  
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
